config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "products#index"
  get "/products/:id/buy", to: "products#buy", as: "buy"
  get "/checkout", to: "products#checkout", as: "checkout"
  get "products.json", to: "products#list"
  get "/products", to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :price, comparison:{greater_than: 0}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        if session[:cart].nil?
            session[:cart] = []
        end
        @products = Product.all
        @cart = session[:cart]
    end

  ##  def buy
  ##      if session[:cart].nil?
  ##          session[:cart] = []
  ##      end
  ##      product = Product.find([params[:id]])
  ##      session[:cart].append(product)
  ##      redirect_to :root
  ##  end

    def checkout
        @cart = session[:cart]
        # empty the shopping cart
        session[:cart] = []
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
        @products = Product.all
        if session[:cart].nil?
          session[:cart] = []
        end
        @cart = session[:cart]
        @item_count = session[:cart].values_at.reduce(:+)
  end

  def buy
    if session[:cart].nil?
        session[:cart] = []
    end
    product = Product.find(params[:id])
    session[:cart].append(product)
    redirect_to :products
  end

  def show
    @products = Product.find(params[:id])
    session[:cart].append(product)
    redirect_to :root
  end

  def checkout
    @cart = session[:cart]
    @cart.each do |item|
      p = Product.find(item["id"])
      p.quantity = p.quantity-1
      p.save
    end
    session[:cart] = []
  end

  def list
    # return products as json list
    @products = Product.all
    render json: @products, only: [:id, :name, :quantity, :price]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1>Welcome to my Webstore</h1>

We have <%= @products.count %> products and counting

<p>
<%= link_to "Click here to see all our products!", products_path, class: "btn btn-primary" %></button>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fengwebstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/checkout.html.erb
<h1>Your Cart:</h1>

<ul>
<% @cart.each do |products| %>
    <li><%= products["name"]%></li>
<% end %>
</ul>
<%= link_to "Home", root_path%>

app/views/products/index.html.erb
<h1>Products Page</h1>

We have <%= @products.count %> products.

<p>
  <% @products.each do |products| %>
    <li><%=products.name%>: $<%= products.price %>
    <br>Product Description: <%=products.description%>
    <br>Quantity: <%=products.quantity%> left
    <br><%=image_tag products.image, width: "100px"%>
    </li>
      <%= link_to "add to cart", buy_path(products), class: "btn btn-primary"%>
  <br>
  <% end %>
</p>

<h2> your shopping cart has <%= @cart.length%> items</h2>
<%= link_to "Check out", checkout_path%>

<p>
<%= link_to "Home", root_path, class: "btn btn-primary"%></button>
</p>

app/views/products/show.html.erb
<h1><%= @products.name%></h1>